version: 2

updates:
- package-ecosystem: docker
  directories: [ /, .docker ]
  schedule:
    interval: monthly
- package-ecosystem: docker-compose
  directories: [ /, .docker ]
  schedule:
    interval: monthly
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
- package-ecosystem: npm
  schedule:
    interval: monthly
  directory: /
