name: GitHub Pages
# Build and deploy Next.js site to GitHub Pages

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches: [main, master]
    tags: [latest, v*.*.*]
  pull_request:
    branches: [main, master]
    types: [synchronize]
  repository_dispatch:
    types: [pages, github-pages]
  workflow_dispatch:
    inputs:
      node-version:
        default: '24.x'
        description: 'Which version of Node.js to use'
        required: false
        type: string
      npm-version:
        default: 11
        description: 'Which version of NPM to use'
        required: false
        type: number

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: ${{ github.event.inputs.node-version || 24 }}
      NPM_VERSION: ${{ github.event.inputs.npm-version || 11 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: "npm"
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup the Cache
        id: cache
        uses: actions/cache@v5
        with:
          path: |
            app/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: nextjs-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            nextjs-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
      - name: Install dependencies
        run: npm ci
      - name: Build the workspace
        run: npm run build
      - name: Upload the build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: nextjs-build
          path: ./app/build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./app/build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

